version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    expose:
      - '3001'
    ports:
      - '3001:3001'
    environment:
      APP_ENV: dev
      PORT: 3001
    links:
      - garage_database:database
    depends_on:
      - garage_database
    command: yarn dev
    networks:
      main:
        aliases:
          - backend

  garage_database:
    container_name: garage_database
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./.data/mongo:/var/lib/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=garage-db
    networks:
      main:
        aliases:
          - garage_database

networks:
  main:
